<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class FaqSeeder extends Seeder
{
    public function run()
    {
        $faq = [
            [
                'id' => 1,
                'idservis' => 1,
                'question' => 'Siapa yang layak memohon IP?',
                'answer' => '<p>Kakitangan UKM yang memerlukan IP untuk sistem, server atau peranti khas sahaja</p>',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-09 08:41:44',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 2,
                'idservis' => 1,
                'question' => 'Berapa lama proses kelulusan?',
                'answer' => 'Kebiasaannya 1–3 hari bekerja selepas permohonan lengkap.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 3,
                'idservis' => 1,
                'question' => 'Adakah IP ini kekal?',
                'answer' => 'Tidak, IP akan disemak semula secara berkala mengikut keperluan.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 4,
                'idservis' => 2,
                'question' => 'Siapa layak memohon elaun komputer?',
                'answer' => 'Kakitangan tetap UKM mengikut syarat yang ditetapkan.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 5,
                'idservis' => 2,
                'question' => 'Dokumen apa diperlukan?',
                'answer' => 'Borang permohonan dan dokumen sokongan pembelian.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 6,
                'idservis' => 2,
                'question' => 'Berapa lama proses tuntutan?',
                'answer' => 'Bergantung kepada kelulusan kewangan, biasanya 14–30 hari.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 7,
                'idservis' => 3,
                'question' => 'Lokasi mana boleh dipasang?',
                'answer' => 'Bangunan dan ruang rasmi UKM sahaja.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 8,
                'idservis' => 3,
                'question' => 'Siapa menanggung kos pemasangan?',
                'answer' => 'Bergantung kepada kelulusan dan bajet jabatan.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 9,
                'idservis' => 3,
                'question' => 'Adakah penyelenggaraan disediakan?',
                'answer' => 'Ya, penyelenggaraan disediakan oleh pihak ICT.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 10,
                'idservis' => 4,
                'question' => 'Perlu mohon berapa awal?',
                'answer' => 'Sekurang-kurangnya 3 hari sebelum acara.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 11,
                'idservis' => 4,
                'question' => 'Peralatan apa disediakan?',
                'answer' => 'Kamera, audio, streaming dan sokongan teknikal.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 12,
                'idservis' => 4,
                'question' => 'Adakah sokongan semasa acara?',
                'answer' => 'Ya, bergantung kepada skop permohonan.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 13,
                'idservis' => 5,
                'question' => 'Perisian apa boleh dimohon?',
                'answer' => 'Perisian rasmi, berlesen dan diluluskan UKM.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 14,
                'idservis' => 5,
                'question' => 'Adakah perisian percuma disokong?',
                'answer' => 'Ya, tertakluk kepada kesesuaian penggunaan.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 15,
                'idservis' => 5,
                'question' => 'Siapa yang meluluskan?',
                'answer' => 'Unit ICT dan pihak pengurusan berkaitan.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 16,
                'idservis' => 6,
                'question' => 'Siapa perlu ID SMU?',
                'answer' => 'Kakitangan baharu atau pengguna sistem UKM.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 17,
                'idservis' => 6,
                'question' => 'Berapa lama ID diaktifkan?',
                'answer' => 'Biasanya dalam 1 hari bekerja.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 18,
                'idservis' => 6,
                'question' => 'Boleh guna untuk semua sistem?',
                'answer' => 'Ya, untuk sistem dalaman UKM.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 19,
                'idservis' => 7,
                'question' => 'Bila perlu buat penamatan?',
                'answer' => 'Apabila kakitangan tamat perkhidmatan.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 20,
                'idservis' => 7,
                'question' => 'Siapa bertanggungjawab mohon?',
                'answer' => 'Ketua jabatan / pentadbir.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 21,
                'idservis' => 7,
                'question' => 'Apa risiko jika tidak ditamatkan?',
                'answer' => 'Risiko keselamatan dan akses tanpa kebenaran.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 22,
                'idservis' => 8,
                'question' => 'Peralatan apa boleh dipinjam?',
                'answer' => 'Laptop, projektor, kamera dan peralatan ICT terhad.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 23,
                'idservis' => 8,
                'question' => 'Tempoh pinjaman maksimum?',
                'answer' => 'Bergantung kepada kelulusan, biasanya 1–7 hari.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 24,
                'idservis' => 8,
                'question' => 'Jika rosak atau hilang?',
                'answer' => 'Peminjam bertanggungjawab sepenuhnya.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 25,
                'idservis' => 9,
                'question' => 'Apakah skop multimedia?',
                'answer' => 'Video, grafik, fotografi dan suntingan.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 26,
                'idservis' => 9,
                'question' => 'Perlu brief awal?',
                'answer' => 'Ya, untuk elak salah faham hasil akhir.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 27,
                'idservis' => 9,
                'question' => 'Boleh minta pindaan?',
                'answer' => 'Ya, bergantung kepada masa dan skop.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 28,
                'idservis' => 10,
                'question' => 'Apa itu laluan khas?',
                'answer' => 'Akses rangkaian khas untuk sistem tertentu.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 29,
                'idservis' => 10,
                'question' => 'Siapa layak memohon?',
                'answer' => 'Kakitangan dengan keperluan rasmi.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 30,
                'idservis' => 10,
                'question' => 'Adakah akses kekal?',
                'answer' => 'Tidak, tertakluk kepada semakan.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 31,
                'idservis' => 11,
                'question' => 'Apa itu PEKA?',
                'answer' => 'Penyelenggaraan dan sokongan aplikasi UKM.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 32,
                'idservis' => 11,
                'question' => 'Siapa boleh mohon?',
                'answer' => 'Pemilik atau pentadbir sistem.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 33,
                'idservis' => 11,
                'question' => 'Adakah melibatkan kos?',
                'answer' => 'Bergantung kepada skop kerja.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 34,
                'idservis' => 12,
                'question' => 'Bila akaun dibuat?',
                'answer' => 'Selepas kelulusan HR dan ICT.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 35,
                'idservis' => 12,
                'question' => 'Kapasiti emel berapa?',
                'answer' => 'Mengikut polisi semasa UKM.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 36,
                'idservis' => 12,
                'question' => 'Boleh akses luar kampus?',
                'answer' => 'Ya.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 37,
                'idservis' => 13,
                'question' => 'Siapa layak?',
                'answer' => 'Semua pelajar berdaftar.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 38,
                'idservis' => 13,
                'question' => 'Bila akaun aktif?',
                'answer' => 'Selepas pendaftaran pelajar disahkan.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 39,
                'idservis' => 13,
                'question' => 'Digunakan untuk apa?',
                'answer' => 'Komunikasi rasmi akademik.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 40,
                'idservis' => 14,
                'question' => 'Untuk sistem apa?',
                'answer' => 'Sistem rasmi dan penyelidikan UKM.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 41,
                'idservis' => 14,
                'question' => 'Siapa urus penyelenggaraan?',
                'answer' => 'Unit ICT.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 42,
                'idservis' => 14,
                'question' => 'Ada backup?',
                'answer' => 'Ya, backup berkala.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 43,
                'idservis' => 15,
                'question' => 'Data jenis apa boleh dipohon?',
                'answer' => '<p>Data rasmi dan diluluskan UKM.</p>',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-09 08:41:16',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 44,
                'idservis' => 15,
                'question' => 'Perlu kelulusan khas?',
                'answer' => 'Ya, bergantung sensitiviti data.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 45,
                'idservis' => 15,
                'question' => 'Boleh kongsi dengan pihak luar?',
                'answer' => 'Tidak tanpa kebenaran bertulis.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 46,
                'idservis' => 16,
                'question' => 'Siapa layak?',
                'answer' => 'Fakulti, jabatan dan unit rasmi.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 47,
                'idservis' => 16,
                'question' => 'Template disediakan?',
                'answer' => 'Ya, mengikut standard UKM.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 48,
                'idservis' => 16,
                'question' => 'Siapa kemas kini kandungan?',
                'answer' => 'Pentadbir laman yang dilantik.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 49,
                'idservis' => 17,
                'question' => 'Untuk apa server digunakan?',
                'answer' => 'Sistem dalaman dan aplikasi rasmi.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 50,
                'idservis' => 17,
                'question' => 'Siapa urus keselamatan?',
                'answer' => 'Unit ICT.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 51,
                'idservis' => 17,
                'question' => 'Ada pemantauan?',
                'answer' => 'Ya, 24/7 monitoring.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 52,
                'idservis' => 18,
                'question' => 'Untuk domain apa?',
                'answer' => '<p>Domain berkaitan UKM.</p>',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-22 03:49:25',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 53,
                'idservis' => 18,
                'question' => 'Perlu justifikasi?',
                'answer' => 'Ya.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 54,
                'idservis' => 18,
                'question' => 'Berapa lama proses?',
                'answer' => '1–3 hari bekerja.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 55,
                'idservis' => 19,
                'question' => 'Apa itu UAT?',
                'answer' => 'Ujian penerimaan pengguna.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 56,
                'idservis' => 19,
                'question' => 'Bila UAT dibuat?',
                'answer' => 'Sebelum sistem go-live.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 57,
                'idservis' => 19,
                'question' => 'Siapa terlibat?',
                'answer' => 'Pemilik sistem dan pengguna akhir.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 58,
                'idservis' => 20,
                'question' => 'Wajib untuk semua perolehan?',
                'answer' => 'Ya, bagi perolehan ICT.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 59,
                'idservis' => 20,
                'question' => 'Tujuan kelulusan?',
                'answer' => 'Pastikan spesifikasi teknikal sesuai.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 60,
                'idservis' => 20,
                'question' => 'Siapa meluluskan?',
                'answer' => 'Unit teknikal ICT UKM.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 61,
                'idservis' => 21,
                'question' => 'VPN digunakan untuk apa?',
                'answer' => 'Akses sistem dalaman dari luar kampus.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 62,
                'idservis' => 21,
                'question' => 'Siapa layak?',
                'answer' => 'Kakitangan dan pelajar terpilih.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
            [
                'id' => 63,
                'idservis' => 21,
                'question' => 'Perlu pasang perisian?',
                'answer' => 'Ya, perisian VPN rasmi.',
                'created_at' => '2026-01-06 22:27:39',
                'updated_at' => '2026-01-06 22:27:39',
                'is_pinned' => 0,
                'sort_order' => 0,
            ],
        ];

        // Memasukkan data ke dalam jadual 'faq'
        $this->db->table('faq')->insertBatch($faq);
    }
}