<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ServisSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'idservis'      => 1,
                'namaservis'    => 'Permohonan IP ',
                'status'        => 1,
                'infourl'       => 'https://appsmu.ukm.my/mohonip',
                'mohonurl'      => 'https://appsmu.ukm.my/mohonip',
                'kodkump'       => '1',
                'kodservis'     => '',
                'infoperincian' => NULL,
                'imejkad'       => 'icon-ip.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 2,
                'namaservis'    => 'Permohonan Elaun Komputer ',
                'status'        => 1,
                'infourl'       => 'https://sistem.ukm.my/khidmat',
                'mohonurl'      => 'https://sistem.ukm.my/khidmat',
                'kodkump'       => '1',
                'kodservis'     => '',
                'infoperincian' => NULL,
                'imejkad'       => 'icon-elaunpc.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 3,
                'namaservis'    => 'Permohonan Pemasangan Talian Internet',
                'status'        => 1,
                'infourl'       => 'http://appsmu.ukm.my/etalian/',
                'mohonurl'      => 'http://appsmu.ukm.my/etalian/',
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => 'Perincian Talian Internet',
                'imejkad'       => 'icon-talian.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 4,
                'namaservis'    => 'Permohonan Perkhidmatan Telesidang / Streaming / Teknikal Acara',
                'status'        => 1,
                'infourl'       => 'https://docs.google.com/forms/d/e/1FAIpQLSeag5nAwSVTg_kKLn0yJzP6GfIwAwnQlDzn7eM3lbJbU-VQAQ/viewform',
                'mohonurl'      => NULL,
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => NULL,
                'imejkad'       => 'icon-acara.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 5,
                'namaservis'    => 'Permohonan Perisian',
                'status'        => 1,
                'infourl'       => 'https://docs.google.com/forms/d/e/1FAIpQLSdV1A1dsD-su-3SJu7amKYu5bo7iepjV4PfpweF-3vjR8cYuQ/viewform',
                'mohonurl'      => NULL,
                'kodkump'       => '3',
                'kodservis'     => NULL,
                'infoperincian' => NULL,
                'imejkad'       => 'icon-perisian.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 6,
                'namaservis'    => 'Permohonan Pengenalan ID SMU (iSIP)',
                'status'        => 1,
                'infourl'       => 'https://appsmu.ukm.my/isip/',
                'mohonurl'      => 'https://appsmu.ukm.my/isip/',
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => NULL,
                'imejkad'       => 'icon-mohonid.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 7,
                'namaservis'    => 'Penamatan Pengenalan ID SMU',
                'status'        => 1,
                'infourl'       => 'https://spdukm.ukm.my/spk/spkppp/_layouts/WordViewer.aspx?id=/spk/spkppp/ptm/UKM-SPKPPP-PT(P)03-PTM-AK02-GP06-BO01 Borang Penamatan Pengenalan SMU.docx&Source=https%3A%2F%2Fspdukm%2Eukm%2Emy%2Fspk%2Fspkppp%2Fptm%2FForms%2FMain%2Easpx%3FGroupString%3D%253B%2523AK02%2520Arahan%2520Kerja%2520Perkhidmatan%2520ICT%253B%252303%252E%2520Borang%253B%2523%26IsGroupRender%3DTRUE&DefaultItemOpen=1',
                'mohonurl'      => '',
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => NULL,
                'imejkad'       => 'icon-tamatid.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 8,
                'namaservis'    => 'Permohonan Pinjaman Peralatan ICT',
                'status'        => 1,
                'infourl'       => 'pinjaman',
                'mohonurl'      => NULL,
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => 'Perincian Pinjaman Peralatan ICT',
                'imejkad'       => 'icon-pinjamalat.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 9,
                'namaservis'    => 'Permohonan Multimedia',
                'status'        => 1,
                'infourl'       => 'https://forms.gle/q8XRLtEW1ALJQUH7A',
                'mohonurl'      => NULL,
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => NULL,
                'imejkad'       => 'icon-mmedia.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 10,
                'namaservis'    => 'Permohonan Laluan Khas',
                'status'        => 1,
                'infourl'       => 'main/laluanvpn',
                'mohonurl'      => NULL,
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => 'Perincian Permohonan Laluan Khas',
                'imejkad'       => 'icon-vpn.png',
                'imejheader'    => 'header-vpn.jpg',
            ],
            [
                'idservis'      => 11,
                'namaservis'    => 'Permohonan PEKA (Penyelenggaraan Aplikasi)',
                'status'        => 1,
                'infourl'       => 'https://smk.ukm.my/peka/',
                'mohonurl'      => 'http://smk.ukm.my/peka',
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => NULL,
                'imejkad'       => 'icon-peka.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 12,
                'namaservis'    => 'Permohonan E-mel Kakitangan',
                'status'        => 1,
                'infourl'       => 'https://appsmu.ukm.my/spek/',
                'mohonurl'      => 'https://appsmu.ukm.my/spek',
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => NULL,
                'imejkad'       => 'icon-emelkktgn.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 13,
                'namaservis'    => 'Permohonan E-mel Pelajar',
                'status'        => 1,
                'infourl'       => 'https://appsmu.ukm.my/speep',
                'mohonurl'      => NULL,
                'kodkump'       => '2',
                'kodservis'     => NULL,
                'infoperincian' => NULL,
                'imejkad'       => 'icon-emelpelajar.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 14,
                'namaservis'    => 'Permohonan Pengwujudan Pangkalan Data',
                'status'        => 1,
                'infourl'       => NULL,
                'mohonurl'      => NULL,
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => NULL,
                'imejkad'       => 'icon-db.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 15,
                'namaservis'    => 'Permohonan Data',
                'status'        => 1,
                'infourl'       => NULL,
                'mohonurl'      => NULL,
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => NULL,
                'imejkad'       => 'icon-data.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 16,
                'namaservis'    => 'Permohonan Tapak Web',
                'status'        => 1,
                'infourl'       => 'http://www.ukm.my/daftarweb',
                'mohonurl'      => NULL,
                'kodkump'       => '3',
                'kodservis'     => NULL,
                'infoperincian' => NULL,
                'imejkad'       => 'icon-tapakweb.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 17,
                'namaservis'    => 'Permohonan Penyediaan Server Dalaman',
                'status'        => 1,
                'infourl'       => NULL,
                'mohonurl'      => NULL,
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => NULL,
                'imejkad'       => 'icon-server.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 18,
                'namaservis'    => 'Permohonan DNS',
                'status'        => 1,
                'infourl'       => 'https://ptm.ukm.my/wp-content/uploads/2017/03/BorangPermohonanDNS.pdf',
                'mohonurl'      => NULL,
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => NULL,
                'imejkad'       => 'icon-dns.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 19,
                'namaservis'    => 'Permohonan UAT',
                'status'        => 1,
                'infourl'       => NULL,
                'mohonurl'      => NULL,
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => NULL,
                'imejkad'       => 'icon-uat.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 20,
                'namaservis'    => 'Permohonan Kelulusan Teknikal Perolehan ICT UKM',
                'status'        => 1,
                'infourl'       => 'https://docs.google.com/forms/d/e/1FAIpQLSf49bsniiwZKM7PbWNJ4OUMQwy7YWrYqeKlRpCmZ0HtB6bJXw/viewform',
                'mohonurl'      => NULL,
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => NULL,
                'imejkad'       => 'icon-teknikal.png',
                'imejheader'    => NULL,
            ],
            [
                'idservis'      => 21,
                'namaservis'    => 'Permohonan VPN UKM',
                'status'        => 1,
                'infourl'       => 'main/laluanvpn',
                'mohonurl'      => NULL,
                'kodkump'       => '1',
                'kodservis'     => NULL,
                'infoperincian' => 'Perincian VPN',
                'imejkad'       => 'icon-vpn.png',
                'imejheader'    => NULL,
            ],
        ];

        // Insert semua data sekaligus
        $this->db->table('aict4u103dservis')->insertBatch($data);
    }
}
